### PR TITLE
Feature/telegram support 0.23.3

### PR DESCRIPTION
**Pull request by phillipadsmith**
Upgrades Telegram to the node-telegram-api 0.23.3 (with Bot 2.0 support). Removes monkey patch. Fixes .stop() method.

### CODE REVIEW

**Comment by phillipadsmith** [comment]
Oh, yikes, that's a terrible PR. :-(

**Comment by mrkno** [comment]
Please resolve merge conflicts with master

**Comment by phillipadsmith** [comment]
Oh, I see what happened... one second.

**Comment by phillipadsmith** [comment]
Ignore this one, I'll send a new one. I started with the wrong branch.

**Pull request closed without merging**
